### PR TITLE
16/Add meteorites

### PR DESCRIPTION
**Pull request by Davidek776**
### THE Checklist:
- [x] I have review my code
- [x] I have removed unnecessary comments
- [x] I have merged my **branch** scene into the **main** scene
- [x] I have tested that the app works after merging into the main scene (in Unity is enough)

Every 30 second it spawns the Asteroid that is flying directly to rocket.

https://github.com/user-attachments/assets/dbb0ce0f-cb1d-4d24-ad77-0ff8310e8b0c

### CODE REVIEW

**Comment by simonfrayer** [comment]
I don't think this is really something I had in mind. I would preffer if you could do like an asteroid **field** that would stay in place for the MVP and then afterwords we could implement it some movement logic once we have a game boundary or something.

The idea is to end up with samething like that when we have the cruiser as well: 

image

image

image

**Comment by Davidek776** [comment]
Ok, now I understand. For the purpose of MVP I will include in this PR just asteroid prefab and script with asteroid rotation.

I will include spawning of meteorites in different PR, because it will be a bix complex, because we have to continuously spawn them in front of the rocket and then remove them.

**Comment by simonfrayer** [comment]
> Ok, now I understand. For the purpose of MVP I will include in this PR just asteroid prefab and script with asteroid rotation.
> 
> I will include spawning of meteorites in different PR, because it will be a bix complex, because we have to continuously spawn them in front of the rocket and then remove them.

Yeah that's also something I understood differently, I would see 2 possible scenarios:

1. Add the meteorite field in the scene manually (not spawning). just add them somewhere close to the spaceship (preferably in front of it), that will do good for both MVP and final hand-in (you can make multiple fields if you would like, if you just make a prefab out of one).
2. If you feel like you have more ime after we are done with the final hand-in tasks you can implement spawning and movement of the meteorites (however it does not need to spawn in front of the spaceshit or go in its direction).

To give you a bit of a context: We discussed we want to have liek a valid playable are, which would effectively be either a cube or a sphere and if you go out of this playable are it will prompt you to go back inside, if not within a certain amout of time, the spaceship will respawn inside it automatically. So essentially we will end up with all the space objects like meteorites and cruisers inside of the playable area. We do not have it for now, so for now just put it close to the spaceship's starting point.

Also, to the 1st point. I would liek to have the meteorite field as part of the MVP (so done asap), so thats why I was suggesting you to fit it into this PR, essentially you only need to take the prefab you created and place it manually into the scene (maybe create another prefab meteorite field and add that a few times). Just so the game gets a bit more realistic.

**Comment by Davidek776** [comment]
> > Ok, now I understand. For the purpose of MVP I will include in this PR just asteroid prefab and script with asteroid rotation.
> > I will include spawning of meteorites in different PR, because it will be a bix complex, because we have to continuously spawn them in front of the rocket and then remove them.
> 
> Yeah that's also something I understood differently, I would see 2 possible scenarios:
> 
> 1. Add the meteorite field in the scene manually (not spawning and stationary, only rotating alongise their own axis). just add them somewhere close to the spaceship (preferably in front of it), that will do good for both MVP and final hand-in (you can make multiple fields if you would like, if you just make a prefab out of one).
> 2. If you feel like you have more ime after we are done with the final hand-in tasks you can implement spawning and movement of the meteorites (however it does not need to spawn in front of the spaceshit or go in its direction).
> 
> To give you a bit of a context: We discussed we want to have liek a valid playable are, which would effectively be either a cube or a sphere and if you go out of this playable are it will prompt you to go back inside, if not within a certain amout of time, the spaceship will respawn inside it automatically. So essentially we will end up with all the space objects like meteorites and cruisers inside of the playable area. We do not have it for now, so for now just put it close to the spaceship's starting point.
> 
> Also, to the 1st point. I would liek to have the meteorite field as part of the MVP (so done asap), so thats why I was suggesting you to fit it into this PR, essentially you only need to take the prefab you created and place it manually into the scene (maybe create another prefab meteorite field and add that a few times). Just so the game gets a bit more realistic.

Ok, I understand. I'm going to create field prefab and place it close to the spaceship.

**Comment by Davidek776** [comment]
> > > Ok, now I understand. For the purpose of MVP I will include in this PR just asteroid prefab and script with asteroid rotation.
> > > I will include spawning of meteorites in different PR, because it will be a bix complex, because we have to continuously spawn them in front of the rocket and then remove them.
> > 
> > 
> > Yeah that's also something I understood differently, I would see 2 possible scenarios:
> > 
> > 1. Add the meteorite field in the scene manually (not spawning and stationary, only rotating alongise their own axis). just add them somewhere close to the spaceship (preferably in front of it), that will do good for both MVP and final hand-in (you can make multiple fields if you would like, if you just make a prefab out of one).
> > 2. If you feel like you have more ime after we are done with the final hand-in tasks you can implement spawning and movement of the meteorites (however it does not need to spawn in front of the spaceshit or go in its direction).
> > 
> > To give you a bit of a context: We discussed we want to have liek a valid playable are, which would effectively be either a cube or a sphere and if you go out of this playable are it will prompt you to go back inside, if not within a certain amout of time, the spaceship will respawn inside it automatically. So essentially we will end up with all the space objects like meteorites and cruisers inside of the playable area. We do not have it for now, so for now just put it close to the spaceship's starting point.
> > Also, to the 1st point. I would liek to have the meteorite field as part of the MVP (so done asap), so thats why I was suggesting you to fit it into this PR, essentially you only need to take the prefab you created and place it manually into the scene (maybe create another prefab meteorite field and add that a few times). Just so the game gets a bit more realistic.
> 
> Ok, I understand. I'm going to create field prefab and place it close to the spaceship.


https://github.com/user-attachments/assets/450e3e14-34b3-4b7f-80e2-08a53bbfb751

**Comment by Davidek776** [comment]
> Cool, if it work it works!

Yes, I think the same. Regarding that issue that you mentioned that enemies would have collision with meteorites, then you can see on the video that it isn't issue at all. 

https://github.com/user-attachments/assets/6287f776-be89-410b-8e1d-dcdf446bad41

**Pull request merged**
